#!/bin/bash

FONT="JetBrainsMono Nerd Font:Regular:13.0"
PADDINGS=6

BAR_BG=0xff11221C
BAR_BORDER=0x00000000
ITEM_BG=0x00000000
ITEM_FG=0xffe6d8ba
ACCENT=0xff71CEAD

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

sketchybar --bar height=32 \
                 color=$BAR_BG \
                 border_color=$BAR_BORDER \
                 position=top \
                 sticky=on \
                 topmost=off \
                 y_offset=0 \
                 corner_radius=0 \
                 padding_left=8 \
                 padding_right=8

default=(
  icon.font="$FONT"
  label.font="$FONT"
  icon.color=$ITEM_FG
  label.color=$ITEM_FG
  background.color=$ITEM_BG
  background.corner_radius=0
  background.height=24
  icon.padding_left=$PADDINGS
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=$PADDINGS
  padding_left=2
  padding_right=2
)

sketchybar --default "${default[@]}"
sketchybar --add event aerospace_workspace_change

for sid in 1 2 3 4 5 6 7 8 9 10
do
  sketchybar --add item space.$sid left \
             --set space.$sid icon="$sid" \
                              icon.color=$ITEM_FG \
                              label.drawing=off \
                              background.color=0x00000000 \
                              background.border_width=0 \
                              click_script="aerospace workspace $sid" \
                              script="$PLUGIN_DIR/space.sh $sid" \
             --subscribe space.$sid aerospace_workspace_change mouse.clicked
done

sketchybar --add item front_app center \
           --set front_app icon.drawing=off \
                           label.color=$ITEM_FG \
                           label.max_chars=40 \
                           script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

sketchybar --add item battery right \
           --set battery update_freq=30 \
                        script="$PLUGIN_DIR/battery.sh"

sketchybar --add item clock right \
           --set clock update_freq=10 \
                     icon="" \
                     script="$PLUGIN_DIR/clock.sh"

sketchybar --update
sketchybar --trigger aerospace_workspace_change
