after-startup-command = ['exec-and-forget ~/.config/borders/bordersrc']
start-at-login = true
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

[gaps]
inner.horizontal = 0
inner.vertical = 0
outer.left = 0
outer.bottom = 0
outer.top = 0
outer.right = 0

[mode.main.binding]
alt-enter = 'exec-and-forget open -na "Ghostty"'
alt-shift-enter = "exec-and-forget osascript -e 'tell application \"Google Chrome\" to make new window' -e 'tell application \"Google Chrome\" to activate'"
alt-shift-m = 'exec-and-forget open -a "Music"'
alt-shift-g = "exec-and-forget osascript -e 'tell application \"Google Chrome\" to open location \"https://github.com\"' -e 'tell application \"Google Chrome\" to activate'"
alt-shift-s = "exec-and-forget osascript -e 'tell application \"Google Chrome\" to open location \"https://app.shortcut.com\"' -e 'tell application \"Google Chrome\" to activate'"
alt-space = 'exec-and-forget open -a "Raycast"'
alt-ctrl-b = 'exec-and-forget open "x-apple.systempreferences:com.apple.BluetoothSettings"'
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'
alt-t = 'layout tiling'
alt-f = 'fullscreen'
cmd-w = 'close'
alt-q = 'close'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-ctrl-h = 'resize width -70'
alt-ctrl-j = 'resize height +70'
alt-ctrl-k = 'resize height -70'
alt-ctrl-l = 'resize width +70'
alt-minus = 'resize smart -60'
alt-equal = 'resize smart +60'
alt-shift-equal = 'resize smart +60'
cmd-minus = 'resize width -60'
cmd-equal = 'resize width +60'
cmd-shift-equal = 'resize width +60'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

alt-tab = 'workspace-back-and-forth'
alt-shift-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']
alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.raycast.macos'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = ['layout tiling']

[[on-window-detected]]
if.app-id = 'com.electron.kumospace'
run = ['layout tiling']
